/**
 * Domain registry — the declared set of knowledge-base domains.
 *
 * A domain is the unit of three things at once:
 *   • access      — one Syncthing folder per domain; a wolf gets a domain's
 *                   folder only if it subscribes (wolf.yaml `domains: []`).
 *   • discovery   — each domain carries its own INDEX.md (generated by Dewey).
 *   • mirroring   — Dewey's host is sendonly; subscribed wolves are receiveonly.
 *
 * Domains are DECLARED (source of truth: ~/.wolfpack/domains.yaml). The CLI is
 * the only writer; Dewey's classifier may only map contributions into declared
 * domains (anything else → _unclassified/, then Dewey recommends a new domain).
 *
 * This file owns the registry's shape, load/save, and validation. The KB base
 * on-disk layout it provisions is:
 *
 *   <KB_BASE>/
 *     domains.yaml                 deployed copy of the registry (Dewey reads)
 *     _unclassified/               quarantine (Dewey-only, never mirrored)
 *     domains/<name>/              ◄── one Syncthing folder (id: kb-<name>)
 *       meta.yaml
 *       INDEX.md
 *       entries/<entry-id>.md
 */

import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { parse as yamlParse, stringify as yamlStringify } from "yaml";

/** Per-domain metadata as declared in the registry. */
export interface DomainEntry {
  /** Human label, e.g. "Snapjack". */
  label: string;
  /** One-line description of what belongs here. */
  description: string;
  /** ISO date (YYYY-MM-DD) the domain was declared. */
  created: string;
}

/** The whole declared registry (what ~/.wolfpack/domains.yaml holds). */
export interface DomainRegistry {
  domains: Record<string, DomainEntry>;
}

const REGISTRY_DIR = path.join(os.homedir(), ".wolfpack");
const REGISTRY_FILE = path.join(REGISTRY_DIR, "domains.yaml");

/** Absolute path to the control-plane domain registry. */
export function registryPath(): string {
  return REGISTRY_FILE;
}

/**
 * Domain names double as directory names AND Syncthing folder ids, so they must
 * be filesystem- and id-safe: lowercase alphanumerics and hyphens, 2–40 chars,
 * not starting/ending with a hyphen. Reserved names are rejected.
 */
const NAME_RE = /^[a-z0-9](?:[a-z0-9-]{0,38}[a-z0-9])?$/;
const RESERVED = new Set(["_unclassified", "entries", "registry", "domains"]);

export function isValidDomainName(name: string): boolean {
  return NAME_RE.test(name) && !RESERVED.has(name);
}

export function assertValidDomainName(name: string): void {
  if (!NAME_RE.test(name)) {
    throw new Error(
      `Invalid domain name "${name}". Use lowercase letters, digits, and ` +
        `hyphens (2–40 chars, no leading/trailing hyphen).`,
    );
  }
  if (RESERVED.has(name)) {
    throw new Error(`"${name}" is a reserved name and cannot be a domain.`);
  }
}

/** The Syncthing folder id for a domain. Stable + globally unique. */
export function domainFolderId(name: string): string {
  return `kb-${name}`;
}

/** Load the registry (empty if none exists yet). */
export function loadRegistry(): DomainRegistry {
  try {
    const raw = fs.readFileSync(REGISTRY_FILE, "utf8");
    const parsed = (yamlParse(raw) ?? {}) as Partial<DomainRegistry>;
    return { domains: parsed.domains ?? {} };
  } catch {
    return { domains: {} };
  }
}

/** Persist the registry atomically. */
export function saveRegistry(reg: DomainRegistry): void {
  fs.mkdirSync(REGISTRY_DIR, { recursive: true });
  const tmp = `${REGISTRY_FILE}.tmp`;
  fs.writeFileSync(tmp, yamlStringify(reg));
  fs.renameSync(tmp, REGISTRY_FILE);
}

export function domainExists(reg: DomainRegistry, name: string): boolean {
  return Object.prototype.hasOwnProperty.call(reg.domains, name);
}

export function listDomainNames(reg: DomainRegistry): string[] {
  return Object.keys(reg.domains).sort();
}

/** Validate a wolf's subscription list against the registry; returns unknowns. */
export function unknownDomains(reg: DomainRegistry, subscribed: string[]): string[] {
  return subscribed.filter((d) => !domainExists(reg, d));
}

/** Today as YYYY-MM-DD (registry timestamps). */
export function today(): string {
  return new Date().toISOString().slice(0, 10);
}

/** Render meta.yaml content for a domain's KB folder. */
export function renderDomainMeta(name: string, e: DomainEntry): string {
  return yamlStringify({
    id: name,
    label: e.label,
    description: e.description,
    created: e.created,
    updated: today(),
  });
}
